### ISSUE TITLE
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by Mennaruuk** [amgedr/webchk#17]
I keep getting this error in webchk, not sure why. It happens sometimes. When I check the output file, I still see good progress, plenty of 200s and 404s, but also a lot of Operation timed outs.

Exception in thread Thread-350 (_process_url):
Traceback (most recent call last):
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python310\lib\site-packages\webchk\__main__.py", line 9, in _process_url
    resp = http_response(url, parse=parse_xml)
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python310\lib\site-packages\webchk\http.py", line 114, in http_response
    result = _http_request(loc, get_request=get_request)
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python310\lib\site-packages\webchk\http.py", line 78, in _http_request
    conn.request(method, loc.path)
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1276, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1322, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1271, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1031, in _send_output
    self.send(msg)
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 969, in send
    self.connect()
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1448, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Users\Menna\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by amgedr** [comment]
Thank you for submitting the bug. Could you please upgrade to the version I uploaded today and try your list of URLs again? It now handles edge cases like these. I also added a timeout option that you might find useful.

**Comment by Mennaruuk** [comment]
It works like a charm!! Thank you so much, and it's so fast! Got 100 URLs checked in merely four seconds. Amazing work!

P.S. How does the timeout option exactly work?

**Comment by amgedr** [comment]
Thank you! I'm very glad you like it.

You can use the timeout option to set how long, in seconds, should webchk wait for the server to respond. If there was no response within that time period the connection will be closed.

**Comment by Mennaruuk** [comment]
Got it. I played around with it, and there seems to be a pattern. Like if I have 100 URLs, maybe it's good to have 10 seconds of timeout. 200 URLs, 20 seconds, and on and on. Works wonderfully!
